### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sicko-gl** [bioboy/slowkicker#3]
Ubuntu 20.04:

$ make
g++ -O2 -Wall -Wextra -pedantic -I/jail/glftpd/bin/sources slowkicker.cpp -o slowkicker
slowkicker.cpp: In function ‘std::string buildPath(const ONLINE&)’:
slowkicker.cpp:324:25: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  324 |         if (filename == '\0') {
      |                         ^~~~
make: *** [Makefile:6: all] Error 1

**Comment by gri1n** [comment]
That should be `if (*filename == '\0') {`

**Comment by bioboy** [comment]
Fixed in master.
